[package]
name = "plugin1"
version = "0.1.0"
edition = "2024"

[dependencies]
amateraview-common.workspace = true
amateraview-connection.workspace = true
eyre.workspace = true
semver.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true